[package]
name = "jvm"
version = "0.1.0"
authors = ["mgtlake <mgtlake@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.0"
bitflags = "1.0"
regex = "1"
pest = "2.0"
pest_derive = "2.0"